repos:
-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
    -   id: detect-secrets
        args: ['scan']
        exclude: package.lock.json
-   repo: https://github.com/thoughtworks/talisman
    rev: 'v1.31.0' 
    hooks:
    # either `commit` or `push` support
    -   id: talisman-commit
    - id: talisman-commit
      entry: cmd --githook pre-commit
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Use the ref you want to point at
    hooks:
    -   id: trailing-whitespace
    # -   id: ...